services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - API_URL=https://adria4889.c44.integrator.host/integrator-api/api/
      - API_HOST=adria4889.c44.integrator.host
